include:
    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/push-branch-to-github@1
      inputs:
          github_repo_url: "https://initbiz-machine-user:${GITHUB_MACHINE_USER_WRITE_TOKEN}@github.com/initbiz/newsletter-plugin.git"

    - component: $CI_SERVER_FQDN/operational/gitlab-ci-components/push-tags-to-github@1
      inputs:
          github_repo_url: "https://initbiz-machine-user:${GITHUB_MACHINE_USER_WRITE_TOKEN}@github.com/initbiz/newsletter-plugin.git"