# ===================================
#  Form Behavior Config
# ===================================

name: initbiz.newsletter::lang.title.subscribers
form: ~/plugins/initbiz/newsletter/models/subscriber/fields.yaml
modelClass: Initbiz\Newsletter\Models\Subscriber
defaultRedirect: initbiz/newsletter/subscribers
