# ===================================
#  Form Behavior Config
# ===================================

name: initbiz.newsletter::lang.title.checkboxes
form: ~/plugins/initbiz/newsletter/models/checkboxes/fields.yaml
modelClass: Initbiz\Newsletter\Models\Checkboxes
defaultRedirect: initbiz/newsletter/checkboxes